### ISSUE TITLE
indentRange not working on unbalanced code

### ISSUE THREAD

**Issue by shaunlebron** [rksm/paredit.js#12]
We are trying to use `indentRange` to indent the line at the cursor, when AST is unbalanced:

[Run it here](https://runkit.com/shaunlebron/5956863fd1d50b001a91fefa)

```js
const paredit = require("paredit.js")
const parseWithCursor = (text) => {
  const i = text.indexOf('|');
  return {text: text.replace('|',''), cursor: i === -1 ? null : i};
};
const {text, cursor} = parseWithCursor(`
[[[[[
  |bar
`);

let ast = paredit.parse(text);
paredit.editor.indentRange(ast, text, cursor, cursor).src
```

Expected:

```
[[[[[
     bar
```

Actual:

```
[[[[[
bar
```

**Comment by rksm** [comment]
OK, as of 0.3 I put in an extension that makes the error objects behave more like sexprs.  I think this should be enough to cover unbalanced situations.

**Comment by shaunlebron** [comment]
thanks 👍

**Comment by anmonteiro** [comment]
I've tested 0.3 and I think it's exactly what I was looking for. Thanks!
