### ISSUE TITLE
Multiline string indentation is not preserved

### ISSUE THREAD

**Issue by jasongilman** [rksm/paredit.js#8]
I'm using the Atom lisp-paredit package which is using 0.2.11 of paredit.js. multiline string indentation is not being reserved when reindenting a block of code. Is that a problem in paredit.js or in the package using it?

It reindents from this:

```
(defn foo
  "This
       indentation
                   is 
                      good"
  []
  5)
```

to this:

```
(defn foo
  "This
  indentation
  is 
  good"
  []
  5)
```

**Comment by rksm** [comment]
Thanks, 0.2.12 fixes that

**Comment by jasongilman** [comment]
Thanks for the quick fix.
